export const seatData = [
  {
    seatNumber: "1",
    cubicle: "14",
    zone: "A",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "John Doe",
  },
  {
    seatNumber: "2",
    cubicle: "22",
    zone: "B",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "3",
    cubicle: "8",
    zone: "C",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Jane Smith",
  },
  {
    seatNumber: "4",
    cubicle: "17",
    zone: "A",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "5",
    cubicle: "12",
    zone: "B",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Bob Johnson",
  },
  {
    seatNumber: "6",
    cubicle: "5",
    zone: "C",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "7",
    cubicle: "9",
    zone: "D",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Alice Williams",
  },
  {
    seatNumber: "8",
    cubicle: "20",
    zone: "A",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "9",
    cubicle: "15",
    zone: "B",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Charlie Brown",
  },
  {
    seatNumber: "10",
    cubicle: "11",
    zone: "C",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "11",
    cubicle: "3",
    zone: "D",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Eva Davis",
  },
  {
    seatNumber: "12",
    cubicle: "18",
    zone: "A",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "13",
    cubicle: "7",
    zone: "B",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "David Miller",
  },
  {
    seatNumber: "14",
    cubicle: "4",
    zone: "C",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "15",
    cubicle: "16",
    zone: "D",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Fiona Wilson",
  },
  {
    seatNumber: "16",
    cubicle: "10",
    zone: "A",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "17",
    cubicle: "2",
    zone: "B",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "George Taylor",
  },
  {
    seatNumber: "18",
    cubicle: "13",
    zone: "C",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
  {
    seatNumber: "19",
    cubicle: "6",
    zone: "D",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "occupied",
    personName: "Helen Anderson",
  },
  {
    seatNumber: "20",
    cubicle: "19",
    zone: "A",
    timings: "9:00 AM - 5:00 PM",
    date: "2023-12-17",
    status: "available",
    personName: "",
  },
];
